### ISSUE TITLE
xyz2graph reads the first two lines

### ISSUE THREAD

**Issue by kol0760** [zotko/xyz2graph#5]
The first line of the XYZ file represents the number of atoms, and the second line is a comment line. However, after reviewing the source code, I noticed that it doesn't skip the second line. In my XYZ file, the second line is `-1093.687437_-1093.627040_subfolder004_0435.xyz_37.899117`, which has a special meaning, but it gets read and causes the package to throw an error, stating that `der` is not a valid element.

Therefore, I made the following changes to **xyz2graph.py**:

I replaced:

```python
content = Path(file_path).read_text().strip()
```

with:

```python
content = "\n".join(Path(file_path).read_text().strip().split('\n')[2:]).strip()
```

**Comment by zotko** [comment]
The fix for this issue has been implemented and released in version 3.0.4. You can now update to the latest version using:

```pip install xyz2graph==3.0.4```

Please let me know if you encounter any problems.
